version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    tty: true
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - db_postgres:/db_postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    tty: true
    restart: always
    volumes:
      - db_redis:/db_redis
volumes:
  db_postgres:
  db_redis: